### ISSUE TITLE
Provide alternative Avram versions, and make them transparently available 

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-marc#118]
There will be 3 versions
- core fields, no Solr mapping
- core fields, with Solr mapping
- core + custom fields, with Solr mapping

Note: notify @jorol when it is done.

**Comment by pkiraly** [comment]
@jorol Now there is a distinct directory marc-schema of this repo, where you can find 3 versions of the schema.

**Comment by jorol** [comment]
Great, thanks a lot! I will prepare a new version of MARC::Schema.
