### ISSUE TITLE
PICA: filter out records

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc#137]
Some PICA records should be filtered out because they are internal, deleted... To ensure stable filter rules, these filters should be put/applied in the import script and executed with pica-rs.

Example: filter out "mailbox" records as they are only used internally (example must be run in script as bash expands `!` if directly run at command line):

~~~
pica filter "002@.0 !~ '^a'" sample.dat
~~~

**Comment by nichtich** [comment]
Some more rules which records to filter out [can be found here](https://wiki.k10plus.de/pages/viewpage.action?pageId=451346458):

~~~
002@.0 !~ '^L'  &&     #  Lokales Katalogisat (nur GBV)
002@.0 !~ '^..[iktN]'  #  Datensatz für internen Gebrauch, gelöscht, Verwaltungsdatensatz oder verdeckt
~~~

With [this issue resolved in pica-rs](https://github.com/deutsche-nationalbibliothek/pica-rs/issues/457), the filters can be read by pica-rs from a file with comments for documentation.

**Comment by nichtich** [comment]
Reduction of records to level 0 can also be done in this step with filter argument `--reduce 0....`. To reduce to level 0 and records with PPN (required), call:

    pica filter --file ignore-records.filter '003@?' --reduce 0... input.dat > reduced.dat

and use file `ignore-records.filter`:

    002@.0 !~ '^L' &&
    002@.0 !~ '^..[iktN]' &&
    (002@.0 !~ '^.v' || 021A.a?)

**Comment by pkiraly** [comment]
@nichtich 
* should `002@.0` be interpret as the `0` subfield of `002@`, so it is equivalent to `002@$0` in another notation? 
* what does `021A.a?` mean?
* `!~` comes from Perl, meaning not matching, right? 
* In `filter --file ignore-records.filter '003@?'` the `--file ignore-records.filter` and `'003@?'` are both parameters of filter command, so it should pass only those records in which the first char of 002@$0 is not L, the third character is not i, k, t, or N and the second character is not N or it has 021A$a. I am a little bit confused with the `'003@?'` part. Should it be filter out or filter in?

**Comment by nichtich** [comment]
Yes `002@.0` and `002@$0` is both subfield `0` of `002@` in [PICA Path syntax](https://format.gbv.de/query/picapath). The latter is preferred for display and the former does not require shell escaping. If put in a file as suggested, the syntax with `$` is better indeed. 

`021A.a?` and `!~` are pica-rs filter syntax, see [here](https://github.com/deutsche-nationalbibliothek/pica-rs#filter) and [here](https://deutsche-nationalbibliothek.github.io/pica-rs/book/tutorials/beginner-tutorial.html#filter) for documentation.

> I am a little bit confused with the '003@?' part. Should it be filter out or filter in?

Yes, that's confusing, it's ignored anyway because filter expression is read from file. A next version of pica-rs will get rid of this, so the colling syntax would become

    pica filter --file ignore-records.filter --reduce 0... input.dat > reduced.dat

**Comment by pkiraly** [comment]
For the time being I will not implement the exact syntax, but something which is parsable more easyly, and later I will get back to this feature. There is an existng feature `--ignorableRecords` which expects MARCSpec expressions separated by comma, which means OR, so a record is ignorable if expr1 OR expr2 OR ... exprN fits. If the input is PICA of course it expects PICA path.

**Comment by pkiraly** [comment]
@nichtich I am working on this, and seems that the ´filter` has the opposite meaning than `--ignorableRecords`.

`filter "002@.0 !~ '^a'"` -- lets in records which are not mailboxes
`--ignorableRecords "002@.0 !~ '^a'"` -- leaves out records which are not mailboxes

I see two solutions:
1. reserve the operator so `!~` becomes `=~`. It is not compatible with `filter`, and needs some more development. 
2. add a new parameter `--filterRecords` which would be compatible with `filter`.

Which one do you prefer?

**Comment by nichtich** [comment]
Filtering out records should be left to [pica-rs](https://github.com/deutsche-nationalbibliothek/pica-rs) as far as possible. It's more reliable to have specialized tools for specific tasks, put together as modules.
