### ISSUE TITLE
PICA: Filter out internal fields

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc#144]
This is a list of internal PICA fields that should be ignored. This is best done as preprocessing as part of #137 but I have not figured out how to best do it with pica-rs:

~~~
001@    ILNs der Bibliotheken mit Exemplarsatz
001E    Datum und Uhrzeit der Löschung
001L    UTC-Zeitstempel der letzten Änderung
001U    Unicode-Kennzeichen
001X    Authority owner
001X    Title owner
002V    MRM: Datum/Uhrzeit der Erzeugung der Master-TA
003C    MRM: PPN der bevorzugten Slave-TA
003G    Partner-Dokument-ID (VFL) 
003Z    MRM: lokale ID Lieferant/Quelle
008G    Regional-Kennzeichen
017N    Angaben zum Lizenzierungsprozess von vergriffenen Werken
020F    Inhaltliche Zusammenfassung (lang) 
027D    Titel in Bandsätzen und Aufsätzen (für die Anzeige usw.)
031B    Bestandsangaben zu Mikroform-Master und Printing Master
037I    Angaben zu Benutzungs- und Vervielfältigungsbedingungen
039V    MRM: Link zum Master Record (in Slave-Aufnahme)
042@    offline-Satzmarkierung 
046G    Angaben zum Ausgabevermerk (nur CERL/HPB 1.77)
046T    Hinweise auf parallele Ausgaben (nur CERL/HPB 1.77)
~~~

**Comment by pkiraly** [comment]
The tool have a parameter for it:

`-z [list of tags]`, `--ignorableFields [list of tags]`: do NOT validate the selected fields. The list should contains the tags separated by commas (,), e.g. `--ignorableFields A02,AQN`

I will put the list into the config file: https://github.com/pkiraly/metadata-qa-marc/blob/140-pica-parsing-pica-record/catalogues/k10plus_pica.sh

**Comment by nichtich** [comment]
The list above only covers internal fields on level 0. Level 1 and 2 have additional fields too, e.g. 101@. I'll assign to myself to extend the list.

**Comment by nichtich** [comment]
As far as I could find so far, the following fields are internal use only, so they should be removed as well:

~~~
101@	Besitzende Bibliothek
101E	Kennung und Datum der Löschung
101U	Unicode-Kennzeichen
102D	Quelle (Bearb. bzw. Programm) und Datum der letzten Änderung			
201E	ELN: Datum der logischen Löschung
201U	Unicode-Kennung
202D	Quelle (Bearb. bzw. Programm) und Datum der letzten Änderung
~~~
