### ISSUE TITLE
Adding Gent/Belgium specific MARC tags: 591, 920, 922

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-marc#16]

**Comment by pkiraly** [comment]
The DNB and Gent also use 591 with different definition. It seems right now it is kind of random which wins. Users should use --marcVersion to make sure they use the right version.

**Comment by phochste** [comment]
There isn't a 'right' version for these local fields. Probably the report should ignore all fields which have 9** , *9* The only thing that is sure for these fields is that they should have at least one subfield.

**Comment by pkiraly** [comment]
We can introduce a flag to ignore those fields, such as `--skipNines`. I do not want to get rid of them from the tool for several reasons.
