### ISSUE TITLE
PICA: Parsing PICA Plain with $ in field values

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc#164]
It looks like there is a bug when parsing PICA Plain with `$` in field values, but the error may be in the source data as well.

Example: http://ddb.qa-catalogue.eu/k10plus_pica/?tab=data&query=&query=*:*&filters[]=005Ax20_ss:*

K10plus PPN 129931373 contains field `005A` with (in PICA Plain):

    005A $00263-9254$f: L 230.00 (jährl., EU), $$ 435.00 (jährl.)

The `$` in second subfield `$f` is escaped as `$$`. The subfield value is `: L 230.00 (jährl., EU), $ 435.00 (jährl.)`

In PICA Normalized the subfield indicator is 0x1F instead of `$`, so there is no escaping of `$`.

**Comment by pkiraly** [comment]
I found that there are some strange fields with double dollar sign:

```
037I $aBraunschweig$$nGeorg-Eckert-Institut - Leibniz-Institut für internationale Schulbuchforschung
```
(http://ddb.qa-catalogue.eu/k10plus_pica/?tab=data&query=id%3A1734305185)

according to this parsing rule it will be interpreted as
subfield a = "Braunschweig$nGeorg-Eckert-Institut - Leibniz-Institut für internationale Schulbuchforschung"

**Comment by nichtich** [comment]
The parsing rule and its result for the example is right, but the record content seems wrong.

**Comment by nichtich** [comment]
This seems to be fixed so this issue can be closed, no?

- http://ddb.qa-catalogue.eu/k10plus_pica/?tab=data&query=id%3A129931373 : price parsed with literal `$`
- http://ddb.qa-catalogue.eu/k10plus_pica/?tab=data&query=id%3A1734305185 : parsed right, detected error in catalog data
