### ISSUE TITLE
Uniqueness of PICA field ranges reported wrongly

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc#247]
K10plus PICA field [041A/00-99 (=5100-5199)](https://format.k10plus.de/k10plushelp.pl?cmd=kat&katalog=Standard&val=5100) is not repeatable but it is a range of fields, so each entry of the range can exist once in a record. Current version reports "repetition of non-repeatable field" for any repetition of fields in this range (see for instance PPN 010008039).

This is valid (no repitition in 041A/00-99=5100-5199):

~~~
041A $9106076612
041A/01 $9104589787
041A/02 $zGeschichte <1968-1975>
~~~

This is not valid (`041A/01` twice, so it is a repitition in 041A/00-99=5100-5199 with 2 instances):

~~~
041A $9106076612
041A/01 $9104589787
041A/01 $zGeschichte <1968-1975>
~~~

**Comment by pkiraly** [comment]
Could you confirm that this is also invalid?
```
041A $9106328433 $VTgv1 $7gnd/4017869-9 $3208921451 $AFormentera
041A $9104713690 $VTgv1 $7gnd/4026432-4 $3208966285 $AIbiza
```

**Comment by nichtich** [comment]
Yes, this would also be invalid.
