### ISSUE TITLE
In the CVS/TAB reports provide one line per undefined field

### ISSUE THREAD

**Issue by phochste** [pkiraly/metadata-qa-marc#25]
In the current CSV/TAB reports we get for undefined fields something like:

```
000018483^I^Iundefined field^IFMT, LKR, CAT
```

Can the report not be grouped by field name and just report the errors like:

```
000018483^I^Iundefined field^IFMT
000018483^I^Iundefined field^ILKR
000018483^I^Iundefined field^ICAT
```

**Comment by pkiraly** [comment]
@phochste 
It is there. Please test it.
