### ISSUE TITLE
Creation of id-groupid.csv required for validation

### ISSUE THREAD

**Issue by nichtich** [pkiraly/metadata-qa-marc#253]
both `validate` and `sqlite` require `id-groupid.csv` (if grouping is enabled) but this file is only created with `completeness`. I guess `completeness` should go first in `do_all_analyses` in `common_script`.

**Comment by pkiraly** [comment]
Right now I have a serious problem with the postprocessing of CSV files after validation. It works well for some million records, but when I run it on the full data dump, the process runs for long time. I am working on this, and I will fix this issue when the performance problem will be solved. I beg your patience.

**Comment by nichtich** [comment]
To replicate, run with an empty output directory, otherwise `id-groupid.csv` from previous analyses will be found.

**Comment by pkiraly** [comment]
Yes, it is clear. Completeness creates the is-groupid.csv file. The validation should be modified to create it if it is not yet created.
