### ISSUE TITLE
'all' command should run only the selected tasks if schema is PICA

### ISSUE THREAD

**Issue by pkiraly** [pkiraly/metadata-qa-marc#265]
The supported tasks are
- completeness
-  validate
-  authorities
-  classifications
-  marc-history

`all-analyses-pica` will run these analyses
`all` will run `all-analyses-pica` if the `$SCHEMA` variable is `PICA` ortherwise `all-analyses`, then in both case `all-solr`

**Comment by nichtich** [comment]
The `ANALYSES` variable can be set to `completeness,validate,authorities,classifications,marc-history` to do so.

**Comment by pkiraly** [comment]
Do you mean such like this?

```bash
if [ "${SCHEMA:-}" == "PICA" ]; then
  ALL_ANALYSES=validate,validate_sqlite,completeness,completeness_sqlite,classifications,authorities,marc_history
else
  ALL_ANALYSES=validate,validate_sqlite,completeness,completeness_sqlite,classifications,authorities,tt_completeness,shelf_ready_completeness,serial_score,functional_analysis,pareto,marc_history
fi
ANALYSES=${ANALYSES:-$ALL_ANALYSES}
```

**Comment by pkiraly** [comment]
I saw that and I like it!
