### ISSUE TITLE
MARC Schema: missing tags 

### ISSUE THREAD

**Issue by jorol** [pkiraly/metadata-qa-marc#47]
Missing tags:

- [ ] 09x https://www.loc.gov/marc/bibliographic/bd09x.html

- [ ] 59x https://www.loc.gov/marc/bibliographic/bd59x.html

- [ ] 9xx not part of the standard, but in common use, see https://www.loc.gov/marc/bibliographic/bd9xx.html and https://www.oclc.org/bibformats/en/9xx.html. I'm not sure what's the best way to handle them...

**Comment by pkiraly** [comment]
There is a model to use those elements, but it requires the publication of local tag definitions. The codebase contains the following non MARC21 namespaces:

- Ghent ([de.gwdg.metadataqa.marc.definition.tags.genttags](https://github.com/pkiraly/metadata-qa-marc/tree/master/src/main/java/de/gwdg/metadataqa/marc/definition/tags/genttags)) - for records from Universiteitsbibliotheek Gent
- FENNICA ([de.gwdg.metadataqa.marc.definition.tags.fennicatags](https://github.com/pkiraly/metadata-qa-marc/tree/master/src/main/java/de/gwdg/metadataqa/marc/definition/tags/fennicatags)) - for the Finnish national bibliography
- DNB ([de.gwdg.metadataqa.marc.definition.tags.dnbtags](https://github.com/pkiraly/metadata-qa-marc/tree/master/src/main/java/de/gwdg/metadataqa/marc/definition/tags/dnbtags)) - for the Deutsche Nationalbibliothek database
- OCLC ([de.gwdg.metadataqa.marc.definition.tags.oclctags](https://github.com/pkiraly/metadata-qa-marc/tree/master/src/main/java/de/gwdg/metadataqa/marc/definition/tags/oclctags)) - for the OCLC MARC (it does not cover the complete OCLC Marc, only those I found in usage)
- SZTE ([de.gwdg.metadataqa.marc.definition.tags.sztetags](https://github.com/pkiraly/metadata-qa-marc/tree/master/src/main/java/de/gwdg/metadataqa/marc/definition/tags/sztetags)) - for University of Szeged (Hungary)

So my idea would be that 

1. The custom fields could be defined inside the library
2. The custom fields could be added arbitrary in a configuration file

**Comment by jorol** [comment]
Thanks for the information and links. I'm just using `marc-schema.json` in MARC::Schema. I think I will handle these fields via an enhanced schema definition as you do with the `non MARC21 namespaces`.
